// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: star.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StarGender int32

const (
	StarGender_UNDEFINED StarGender = 0
	StarGender_MALE      StarGender = 1
	StarGender_FEMALE    StarGender = 2
)

// Enum value maps for StarGender.
var (
	StarGender_name = map[int32]string{
		0: "UNDEFINED",
		1: "MALE",
		2: "FEMALE",
	}
	StarGender_value = map[string]int32{
		"UNDEFINED": 0,
		"MALE":      1,
		"FEMALE":    2,
	}
)

func (x StarGender) Enum() *StarGender {
	p := new(StarGender)
	*p = x
	return p
}

func (x StarGender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StarGender) Descriptor() protoreflect.EnumDescriptor {
	return file_star_proto_enumTypes[0].Descriptor()
}

func (StarGender) Type() protoreflect.EnumType {
	return &file_star_proto_enumTypes[0]
}

func (x StarGender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StarGender.Descriptor instead.
func (StarGender) EnumDescriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{0}
}

type Star struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender StarGender `protobuf:"varint,3,opt,name=gender,proto3,enum=model.StarGender" json:"gender,omitempty"`
}

func (x *Star) Reset() {
	*x = Star{}
	if protoimpl.UnsafeEnabled {
		mi := &file_star_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Star) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Star) ProtoMessage() {}

func (x *Star) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Star.ProtoReflect.Descriptor instead.
func (*Star) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{0}
}

func (x *Star) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Star) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Star) GetGender() StarGender {
	if x != nil {
		return x.Gender
	}
	return StarGender_UNDEFINED
}

type StarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Star `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StarList) Reset() {
	*x = StarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_star_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarList) ProtoMessage() {}

func (x *StarList) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarList.ProtoReflect.Descriptor instead.
func (*StarList) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{1}
}

func (x *StarList) GetList() []*Star {
	if x != nil {
		return x.List
	}
	return nil
}

var File_star_proto protoreflect.FileDescriptor

var file_star_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x55, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x31, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_star_proto_rawDescOnce sync.Once
	file_star_proto_rawDescData = file_star_proto_rawDesc
)

func file_star_proto_rawDescGZIP() []byte {
	file_star_proto_rawDescOnce.Do(func() {
		file_star_proto_rawDescData = protoimpl.X.CompressGZIP(file_star_proto_rawDescData)
	})
	return file_star_proto_rawDescData
}

var file_star_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_star_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_star_proto_goTypes = []interface{}{
	(StarGender)(0),  // 0: model.StarGender
	(*Star)(nil),     // 1: model.Star
	(*StarList)(nil), // 2: model.StarList
}
var file_star_proto_depIdxs = []int32{
	0, // 0: model.Star.gender:type_name -> model.StarGender
	1, // 1: model.StarList.list:type_name -> model.Star
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_star_proto_init() }
func file_star_proto_init() {
	if File_star_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_star_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Star); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_star_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_star_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_star_proto_goTypes,
		DependencyIndexes: file_star_proto_depIdxs,
		EnumInfos:         file_star_proto_enumTypes,
		MessageInfos:      file_star_proto_msgTypes,
	}.Build()
	File_star_proto = out.File
	file_star_proto_rawDesc = nil
	file_star_proto_goTypes = nil
	file_star_proto_depIdxs = nil
}
